slideflow/__init__.py
slideflow/errors.py
slideflow/model/base.py
slideflow/project.py

Enables Bayesian hyperparameter searching through SMAC. 
To use, simply replace `P.train()` with `P.smac_search()` and provide the additional argument `smac_configspace`. For example:
```
import slideflow as sf
import ConfigSpace.hyperparameters as cs_hp
from ConfigSpace import ConfigurationSpace
def main(P):
hp = sf.ModelParams(...)
cs = ConfigurationSpace()
cs.add_hyperparameter(cs_hp.UniformIntegerHyperparameter("epochs", 1, 2))
cs.add_hyperparameter(cs_hp.UniformFloatHyperparameter("dropout", 0, 0.5))
best_config = P.smac_search(
...,
smac_configspace=cs
)
```
By default, it will use tile_auc metric for optimization. This can be overriden using the `smac_metric` argument. You can either provide a different metric:
```
P.smac_search(
...,
smac_metric='patient_auc'
)
```
Or, you can …

Bayesian HP optimization

---

slideflow/dataset.py
slideflow/test/dataset_test.py
slideflow/util/__init__.py

Adds performance improvements in nearly all uses of `Dataset` by improving utilization of vectorized functions (via pandas DataFrame). Specifically this changes:
- `Dataset.slides()` no longer performs any filtering, and simply returns the unique (non-empty) slides present in the filtered annotations.
- `Dataset.filtered_annotations` now calculates filters using vectorized comparisons
- Similar performance improvements for `Dataset.verify_annotations_slides()`
Additionally, this adds:
- New unittest for ensuring duplicate slides in annotations are handled correctly
- `Dataset.annotations` can no longer be set directly, to prevent accidentally bypassing annotation validation. Instead, use `Dataset.load_annotations`

Dataset performance improvements (SLID-9)

---

slideflow/dataset.py
slideflow/errors.py
slideflow/io/preservedsite/crossfolds.py
slideflow/test/dataset_test.py

- Adds pyomo/bonmin solver for calculating site-preserved cross-validation, an open-source alternative to CPLEX
- `sf.dataset.split_patients_preserved_site()` accepts a `method` argument which specifies the solver. Can be `'auto'`, `'cplex'`, or `'bonmin'`. If `'auto'`, will attempt to use CPLEX if available (faster), and if not, will default to bonmin.
- `sf.io.preservedsite.crossfolds.generate()` accepts a new `method` argument with the same logic as above.
- `errors.CPLEXNotFoundError` changed to `errors.SolverNotFoundError`, as this may be raised if attempting to use pyomo/bonmin but it is not installed.
- Includes unit tests for the pyomo/bonmin solver

Pyomo/bonmin solver for site-preserved CV

---

slideflow/slide/__init__.py

In some cases, someone may wish to use Slideflow without slide-processing (such as if TFRecords are already generated, or to use other functionality). Presently, however, Slideflow cannot be imported without libvips/pyvips installed.
This change will log an error if pyvips/libvips is not installed, but will allow the module to be imported.

Handle missing pyvips or libvips

---

.gitmodules
README.md
requirements.txt
slideflow/__init__.py
slideflow/dataset.py
slideflow/experimental/embedding_search.py
slideflow/gan/__init__.py
slideflow/gan/interpolate.py
slideflow/gan/search.py
slideflow/gan/tf_utils.py
slideflow/grad/__init__.py
slideflow/grad/plot_utils.py
slideflow/heatmap.py
slideflow/io/__init__.py
slideflow/model/__init__.py
slideflow/model/tensorflow.py
slideflow/model/tensorflow_utils.py
slideflow/mosaic.py
slideflow/norm/__init__.py
slideflow/norm/tensorflow/__init__.py
slideflow/norm/torch/__init__.py
slideflow/project.py
slideflow/project_utils.py
slideflow/sample_actions.py
slideflow/stats.py
slideflow/test/functional.py
slideflow/test/stats_test.py
slideflow/util/__init__.py

Saliency maps are available through a new submodule `slideflow.grad`. The `sf.grad.SaliencyMap` interface coordinates calculation and display of these maps with a variety of functions, using the saliency package backend. As this is an experimental functionality that has a new dependency, it is not imported by default, and must be imported separately.
`SaliencyMap` can be used directly:
``` python
from slideflow.grad import SaliencyMap
model = sf.keras.models.load_model('path')
smap = SaliencyMap(model, class_idx=0)
map_image = smap.integrated_gradients(image)
```
Or the plotting functions `saliency_map_comparison()`, `multi_plot()`, and `comparison_plot()` can be used to plot results. Several additional utility functions are also included to assist with flexible display.
The …

Saliency Maps and StyleGAN2 Integration

---

slideflow/slide/__init__.py

Runtime AttributeError was encountered when reading in slides in JPG format.  Added try/except blocks.

JPG slide wrapper fix

---

slideflow/__init__.py
slideflow/dataset.py
slideflow/model/tensorflow.py
slideflow/model/tensorflow_utils.py
slideflow/model/torch.py
slideflow/model/torch_utils.py
slideflow/slide/__init__.py
slideflow/slide/report.py
slideflow/stats/metrics.py

- SlideReports now include grayspace/whitespace fraction for each extracted image, in the DataFrame `SlideReport.locations`
- `include_loc` argument removed from `.extract_tiles()` functions, as location information is now always included in the returned dict
- Performance improvements in ROI calculations and slide verification
- Previously, `.extract_tiles()` returned an `ExtractionReport` summarizing what tiles were extracted. Thus report is saved as a PDF in the tile extraction directory. The returned report, however, only summarized tile extraction of the last dataset source. If multiple dataset sources had tiles extracted, on the last source was reflected in this report. Now, for simplicity, this function returns a Dict mapping slide paths to `SlideReport` for each slide, including …

Tile extraction & slide report updates

---

slideflow/model/base.py

- Proposed solution to #200 :
- Pass a dict to loss in the format `{'type': loss_type, 'fun': loss_function}`.
- ` loss_function()` must take two positional parameters, `y_true` and `y_pred`.
- `loss_type` must be one of `'cph'`, `'categorical'` and `'linear'`
- Notes:
Perhaps there is a more elegant solution than slicing strings to discover the model type, but that is very simple so I kept it for now.
- Known Problems:
It seems `y_true` comes in the `tf.int64` type by default, a conversion to `tf.float32` is needed.
- Reference:
https://keras.io/api/losses/#creating-custom-losses

Add custom loss at ModelParams support

---

slideflow/model/base.py
slideflow/model/tensorflow.py
slideflow/model/torch.py
slideflow/project.py

Adds custom loss support for both Tensorflow/Keras and PyTorch, as discussed in #200.
Use by supplying a dictionary to the `loss` argument in `sf.ModelParams`, with the keys `type` and `fn`. `type` must be either `'categorical'`, `'linear'`, or `'cph'`, and 'fn' is a callable loss function.
Gists for testing the below functionality are available [here](https://gist.github.com/jamesdolezal/994e60d7a570c70fabb22a0eef5c388e) (TF/Keras) and [here](https://gist.github.com/jamesdolezal/cce6a25731abd88894c93789b8bf17a7) (PyTorch)
For Tensorflow/Keras, the loss function must accept arguments `y_true, y_pred`. `y_true` will not be one-hot encoded. For linear losses, `y_true` may need to be cast to `tf.float32`. An example custom linear loss is given below:
```python
def custom_linear_loss(y_true, …
```

Custom loss

---

README.md
docs/_modules/slideflow/slide.html
requirements.txt
setup.py
slideflow/__init__.py
slideflow/io/tensorflow.py
slideflow/model/tensorflow.py
slideflow/model/torch.py
slideflow/slide/__init__.py
slideflow/slide/backends/__init__.py
slideflow/slide/backends/cucim.py
slideflow/slide/backends/vips.py
slideflow/slide/qc/otsu.py
slideflow/slide/readers/vips.py
slideflow/slide/utils.py
slideflow/stats/metrics.py
slideflow/util/__init__.py
slideflow/workbench/__init__.py
slideflow/workbench/gui_utils/wsi_utils.py
slideflow/workbench/heatmap_widget.py
slideflow/workbench/slide_widget.py

Adds [cuCIM](https://github.com/rapidsai/cucim) support as a slide reading backend.
cuCIM is 2-3x faster for whole-slide image reading, with lighter CPU utilization and about half the memory footprint. On a 24-core CPU, this permits training directly from whole-slide images (without TFRecords) at around 1100 img/s. It is also much easier to install, requiring only pip:
```
pip install slideflow cupy-cuda11x
```
Libvips functionality has been isolated into `sf.slide.backends.vips`, with cuCIM support in `sf.slide.backends.cucim`. The backend is set via the environmental variable `SF_SLIDE_BACKEND`. If this has not been set, Slideflow will default to using cuCIM if available, falling back to libvips otherwise. Both cannot be imported simultaneously due to memory conflicts resulting in …

cuCIM support

---

slideflow/dataset.py
slideflow/slide/utils.py

The xml_to_csv() function looks for any xml files and converts them to csv inside the user-specified ROI folder. The csv files are saved in the same folder. Then, rois() has been modified to look for xml files. If they exit, it will convert the xmls to csv and add the new csv file paths to the roi list.

Add support for XML-formatted ROIs

---

slideflow/mil/eval.py
slideflow/util/tfrecord2idx.py

On databricks with dbfs file storage, *.zip files are not supported. TFRecord index files are written by default as *zip files (using numpy.savez). This PR adds ability to save the index files as non-zip numpy arrays (using numpy.save), if the environmental variable `SF_ALLOW_ZIP` is set to `0`. This needs to be controlled via environmental variable to ensure the setting is propagated to all child processes in multiprocessing pools.
See #245

TFRecord index files without ZIP archive format

---

slideflow/stats/slidemap.py

I have found it difficult to alter the figure legend when making plots in Slideflow because there is not currently a way to access the matplotlib.axes.Axes.legend().
This modification alters the `Slidemap.plot()` function in the following ways:
- Adds `loc` and `ncol` as optional parameters that are then used in `ax.legend()`. Defaults remain the same as they were when hard-coded.
- Adds `legend_kwargs` as a dictionary of kwargs for the `ax.legend()` function
The `scatter_kwargs` are not altered. No other functionalities have been changed.

Customize Slidemap plot figure legends

---

docs-source/source/slide_processing.rst

Adds missing `slideflow.` prefix.
Note there's also a broken link
```
:class:`the WSI API documentation <slideflow.WSI>`
```
at
https://github.com/jamesdolezal/slideflow/blob/26ce5cf0d34b65514223967ffc0628d0b5031d05/docs-source/source/slide_processing.rst?plain=1#L96
I'm not sure whether Sphinx is supposed to support these type of links.

Fix broken links in slide_processing.rst

---

docs-source/pytorch_sphinx_theme/pytorch_sphinx_theme/theme_variables.jinja

When I click "Tutorials" in the header of the slideflow website, I am led to a 404 page. I am hoping this pull request fixes this. Please let me know if other changes are needed. 
This replaces the url https://slideflow.dev/tutorial1.html with https://slideflow.dev/tutorial1/ . The former URL leads to a 404 error.
Thanks for the comprehensive software!! I am looking forward to using this.

Fix url to tutorials in website

---

docs-source/source/tutorial1.rst

this is my first time using slideflow and i had some trouble extracting tiles from slides. after debugging, i realized that the "slide" column in the annotations file must not include the file extension.
if you don't mind, i modified tutorial1 to indicate that the "slide" column must include file names without extensions.
Original:
```
Add a third column "slide" containing the name of the slide associated with the patient.
```
New:
```
Add a third column "slide" containing the name of the slide associated with the patient (without the file extension).
```
the next two lines also show as modified. i put that text on new lines to keep the line width consistent in that section.

indicate that "slide" column does not include extensions

---

slideflow/mil/_params.py
slideflow/mil/data.py
slideflow/mil/train/__init__.py
slideflow/mil/train/_fastai.py

`TrainerConfigFastAI` now has a new argument called `aggregation_level` which defaults to `'slide'`. 
New behaviour `aggregation_level='patient`:
`build_fastai_learner`
• saves `slide_manifest.csv` where each row is a patient
• the variable bags it creates is an array of lists where each element of the array represent a patient and each element a list is a slide from that patient
`BagDataset:__getitem__` now supports this new type of bag. When it recognizes that an item is a list it concatenates the tiles from different slides as if they all came from the same slide (according to the previous implementation)

316 mil slide aggregate

---

slideflow/project.py

There is a minor bug when sorting the names of the epochs.
Currently, if you have 10 epochs, the sorted list will be [epoch1, epoch10, epoch2, ..., epoch9]
This will return the last epoch as "epoch9", which is incorrect and will end up on a different bug when searching the metrics of the last epoch to be reported in Neptune.

Sorting bug

---

slideflow/slide/qc/otsu.py

This is a tiny fix but I still opened a PR in case @jamesdolezal you want to use this branch to add other related fixes. I looked around the code and to me it looks like only Otsu needs this fix.

Small fix: flip mask in outsu if `roi_method == outside`

---

requirements.txt
setup.py

Other libraries have updated to pin >=0.13. 
Based on the [seaborn changelog](https://seaborn.pydata.org/whatsnew/index.html) I can't see any obvious reason for the strict pin.

Change seaborn pin to <0.14

---

slideflow/mil/models/transmil.py
slideflow/slide/wsi.py

`b29abea` Fix a warning in slideflow studio that happens when a remainder is 0
`4a6a8db` is a temporary fix for `TransMIL` which would not work because it does not currently implement `return_attention`

Small fixes

---

slideflow/mil/eval.py
slideflow/mil/models/clam.py

This fix addresses issue #348, fixing the `get_mil_tile_predictions()` function for CLAM models.
This also fixes improper usage of the `inspect.signature` function.

Fix `sf.mil.get_mil_tile_predictions` for CLAM models

---

slideflow/model/extractors/_factory_torch.py

This version differs slightly from the original PR in that it does not require manual editing of feature extractors you want to be compatible. An example of how to enable histogan compatibility:
```python
uni = sf.build_feature_extractor('uni', ...)
uni.force_uint8 = False
uni.inference_mode = False
```

Add compatibility for Histogan
